// ============================================================
// TAG VOCAB — fonte única de verdade das tags do LifeLog
// (Opção C, 07/09/2026) — slug canônico único por conceito,
// EN como língua franca técnica; pt = label de exibição.
// Regras:
//   - tags de post = TEMAS + tag structural do projeto (chips exibem
//     temas; a pill do projeto nos cards vem do campo `project`)
//   - tag == project DEVE existir no frontmatter (structural, p/
//     agregação em /tag/<slug> via tag OR project — check-tags garante)
//   - novo post: só usar slugs daqui (check-tags.py reprova)
// Mantido por scripts/check-tags.py (parse deste arquivo).
// ============================================================

export interface TagDef {
  slug: string;
  pt?: string; // label PT; ausente = exibir o próprio slug
}

export const PROJECT_SLUGS = [
  'arachne', 'dogwalk', 'portfolio', 'capivara', 'tatuengine',
  'seguranca', 'lifelog', 'estudos', 'descobertas', 'yurumi',
] as const;

export const TAG_VOCAB: TagDef[] = [
  // --- projetos (structural; permitidos como tag apenas p/ cross-ref) ---
  { slug: 'arachne', pt: 'Arachne' },
  { slug: 'dogwalk', pt: 'Dogwalk' },
  { slug: 'portfolio', pt: 'Portfólio' },
  { slug: 'capivara', pt: 'Capivara' },
  { slug: 'tatuengine', pt: 'TatuEngine' },
  { slug: 'seguranca', pt: 'Segurança' },
  { slug: 'lifelog', pt: 'LifeLog' },
  { slug: 'estudos', pt: 'Estudos' },
  { slug: 'descobertas', pt: 'Descobertas' },
  { slug: 'yurumi', pt: 'Yurumi' },

  // --- temas A–F ---
  { slug: 'adafactor' },
  { slug: 'agents', pt: 'Agentes' },
  { slug: 'agents-md', pt: 'Agentes-MD' },
  { slug: 'ai', pt: 'IA' },
  { slug: 'ai-jail' },
  { slug: 'alerts', pt: 'Alertas' },
  { slug: 'allowlist' },
  { slug: 'analytics' },
  { slug: 'animation', pt: 'Animação' },
  { slug: 'api' },
  { slug: 'architecture', pt: 'Arquitetura' },
  { slug: 'artifact', pt: 'Artefato' },
  { slug: 'assistant', pt: 'Assistente' },
  { slug: 'astro' },
  { slug: 'asyncio' },
  { slug: 'audit', pt: 'Auditoria' },
  { slug: 'auth' },
  { slug: 'automation', pt: 'Automação' },
  { slug: 'axe-core' },
  { slug: 'backup' },
  { slug: 'bandit' },
  { slug: 'baseline' },
  { slug: 'bash' },
  { slug: 'bfcache' },
  { slug: 'bge' },
  { slug: 'bindings' },
  { slug: 'bitmamba' },
  { slug: 'bitnet' },
  { slug: 'blog' },
  { slug: 'boot' },
  { slug: 'beginning', pt: 'Começo' },
  { slug: 'browser-agent' },
  { slug: 'browser-pool' },
  { slug: 'bug' },
  { slug: 'bug-hunter' },
  { slug: 'build' },
  { slug: 'bvh' },
  { slug: 'bwrap' },
  { slug: 'cache' },
  { slug: 'cascade', pt: 'Cascata' },
  { slug: 'checkpoint' },
  { slug: 'chromadb' },
  { slug: 'chrome' },
  { slug: 'ci' },
  { slug: 'ci-cd' },
  { slug: 'cleanup', pt: 'Limpeza' },
  { slug: 'cloudflare' },
  { slug: 'cockpit' },
  { slug: 'codec' },
  { slug: 'code', pt: 'Código' },
  { slug: 'code-review' },
  { slug: 'code-splitting' },
  { slug: 'colibri' },
  { slug: 'compression', pt: 'Compressão' },
  { slug: 'computer-use' },
  { slug: 'contrast', pt: 'Contraste' },
  { slug: 'configuration', pt: 'Configuração' },
  { slug: 'context-length' },
  { slug: 'continuous-process', pt: 'Processo Contínuo' },
  { slug: 'controlled-component' },
  { slug: 'convergence', pt: 'Convergência' },
  { slug: 'coverage', pt: 'Cobertura' },
  { slug: 'crawl4ai' },
  { slug: 'crlf' },
  { slug: 'cron' },
  { slug: 'crud' },
  { slug: 'css' },
  { slug: 'cua-driver' },
  { slug: 'cuda' },
  { slug: 'd1' },
  { slug: 'dashboard' },
  { slug: 'data' },
  { slug: 'debugging' },
  { slug: 'decision', pt: 'Decisão' },
  { slug: 'dedup' },
  { slug: 'defense-in-depth' },
  { slug: 'dependencies', pt: 'Dependências' },
  { slug: 'deploy' },
  { slug: 'detection', pt: 'Detecção' },
  { slug: 'dev' },
  { slug: 'devops' },
  { slug: 'docker' },
  { slug: 'documentation', pt: 'Documentação' },
  { slug: 'douglas' },
  { slug: 'drill' },
  { slug: 'e2e' },
  { slug: 'ecosystem', pt: 'Ecossistema' },
  { slug: 'email' },
  { slug: 'embeddings' },
  { slug: 'encoding' },
  { slug: 'engine' },
  { slug: 'event-loop' },
  { slug: 'executive' },
  { slug: 'failover' },
  { slug: 'fallback' },
  { slug: 'false-positive', pt: 'Falso Positivo' },
  { slug: 'fase4' },
  { slug: 'fastapi' },
  { slug: 'feedback' },
  { slug: 'findings' },
  { slug: 'finances', pt: 'Finanças' },
  { slug: 'flushsync' },
  { slug: 'focus-trap' },
  { slug: 'frontend' },
  { slug: 'frontmatter' },
  { slug: 'frustration', pt: 'Frustração' },
  { slug: 'fts5' },
  { slug: 'fusejs' },
  { slug: 'games', pt: 'Jogos' },
  { slug: 'gamification', pt: 'Gamificação' },
  { slug: 'gate' },
  { slug: 'gemini' },
  { slug: 'ghost-components' },
  { slug: 'git' },
  { slug: 'github' },
  { slug: 'github-actions' },
  { slug: 'github-api' },
  { slug: 'gitleaks' },
  { slug: 'goal-hamiltonian' },
  { slug: 'gpu' },
  { slug: 'graphify' },
  { slug: 'guardrails' },
  { slug: 'hardening' },
  { slug: 'hash' },
  { slug: 'hermes' },
  { slug: 'hybrid', pt: 'Híbrida' },
  { slug: 'high-availability' },
  { slug: 'honeypot' },
  { slug: 'hub' },
  { slug: 'hydration' },
  { slug: 'i18n' },
  { slug: 'ideation', pt: 'Ideação' },
  { slug: 'identity', pt: 'Identidade' },
  { slug: 'improvement', pt: 'Melhoria' },
  { slug: 'infrastructure', pt: 'Infraestrutura' },
  { slug: 'ingest' },
  { slug: 'integrity', pt: 'Integridade' },
  { slug: 'inventory', pt: 'Inventário' },
  { slug: 'ipv6' },
  { slug: 'isr' },
  { slug: 'javascript' },
  { slug: 'jwt' },
  { slug: 'k3s' },
  { slug: 'kubernetes' },

  // --- temas L–Z ---
  { slug: 'latency', pt: 'Latência' },
  { slug: 'layout' },
  { slug: 'lcp' },
  { slug: 'learning', pt: 'Aprendizado' },
  { slug: 'learning-rate' },
  { slug: 'lessons', pt: 'Lições' },
  { slug: 'lfs' },
  { slug: 'llm' },
  { slug: 'localhost' },
  { slug: 'locomo' },
  { slug: 'loss' },
  { slug: 'markdown' },
  { slug: 'mamba' },
  { slug: 'mapbox-gl' },
  { slug: 'marketplace' },
  { slug: 'maturity', pt: 'Maturidade' },
  { slug: 'mcp' },
  { slug: 'mdx' },
  { slug: 'memory', pt: 'Memória' },
  { slug: 'metadata', pt: 'Metadados' },
  { slug: 'migration', pt: 'Migração' },
  { slug: 'ml' },
  { slug: 'mobile' },
  { slug: 'monitoring', pt: 'Monitoramento' },
  { slug: 'multi-engine' },
  { slug: 'multimodal' },
  { slug: 'nan' },
  { slug: 'narrative', pt: 'Narrativa' },
  { slug: 'navbar' },
  { slug: 'networking', pt: 'Rede' },
  { slug: 'nextjs' },
  { slug: 'no-agent' },
  { slug: 'node' },
  { slug: 'npm' },
  { slug: 'num-ctx' },
  { slug: 'numpy' },
  { slug: 'observability', pt: 'Observabilidade' },
  { slug: 'offline', pt: 'Offline' },
  { slug: 'ollama' },
  { slug: 'open-design' },
  { slug: 'opengrep' },
  { slug: 'ops' },
  { slug: 'optimization' },
  { slug: 'orders', pt: 'Pedidos' },
  { slug: 'owasp' },
  { slug: 'patterns', pt: 'Padrões' },
  { slug: 'path-traversal' },
  { slug: 'payments' },
  { slug: 'pentest' },
  { slug: 'performance' },
  { slug: 'persistence', pt: 'Persistência' },
  { slug: 'pets' },
  { slug: 'phase-field', pt: 'Campo de Fase' },
  { slug: 'pipeline' },
  { slug: 'pix' },
  { slug: 'playwright' },
  { slug: 'pnpm' },
  { slug: 'pool' },
  { slug: 'ports', pt: 'Portas' },
  { slug: 'postgres' },
  { slug: 'pretrain' },
  { slug: 'privacy', pt: 'Privacidade' },
  { slug: 'process', pt: 'Processo' },
  { slug: 'production', pt: 'Produção' },
  { slug: 'progressive-web-app', pt: 'PWA' },
  { slug: 'productivity', pt: 'Produtividade' },
  { slug: 'progress', pt: 'Progresso' },
  { slug: 'projects', pt: 'Projetos' },
  { slug: 'punishment' },
  { slug: 'pytest' },
  { slug: 'pytorch' },
  { slug: 'qa' },
  { slug: 'qdrant' },
  { slug: 'quality', pt: 'Qualidade' },
  { slug: 'quantization', pt: 'Quantização' },
  { slug: 'queue' },
  { slug: 'qwen2.5vl' },
  { slug: 'rag' },
  { slug: 'rate-limit' },
  { slug: 'reasoning', pt: 'Raciocínio' },
  { slug: 'react' },
  { slug: 'react-router' },
  { slug: 'rebuild' },
  { slug: 'redesign' },
  { slug: 'red-team' },
  { slug: 'refactoring', pt: 'Refatoração' },
  { slug: 'reliability' },
  { slug: 'repo' },
  { slug: 'reranker' },
  { slug: 'research' },
  { slug: 'resend' },
  { slug: 'reuse', pt: 'Reuso' },
  { slug: 'review', pt: 'Revisão' },
  { slug: 'rrf' },
  { slug: 'sandbox' },
  { slug: 'scanner' },
  { slug: 'scheduler' },
  { slug: 'schema-drift' },
  { slug: 'scraping' },
  { slug: 'search', pt: 'Busca' },
  { slug: 'secrets' },
  { slug: 'secret-scanning' },
  { slug: 'security', pt: 'Segurança (tema)' },
  { slug: 'security-agent' },
  { slug: 'security-txt' },
  { slug: 'self-hosted' },
  { slug: 'self-improvement' },
  { slug: 'sft' },
  { slug: 'showcase', pt: 'Vitrine' },
  { slug: 'service-worker', pt: 'Service Worker' },
  { slug: 'sidecar' },
  { slug: 'simplicity', pt: 'Simplicidade' },
  { slug: 'skills' },
  { slug: 'socat' },
  { slug: 'sqlalchemy' },
  { slug: 'sqlite-vec' },
  { slug: 'ssm' },
  { slug: 'ssr' },
  { slug: 'stack' },
  { slug: 'starlette' },
  { slug: 'stripe' },
  { slug: 'stt' },
  { slug: 'studies', pt: 'Estudos (tema)' },
  { slug: 'supabase' },
  { slug: 'supply-chain' },
  { slug: 'sync' },
  { slug: 'systemd' },
  { slug: 'tags' },
  { slug: 'taxonomy', pt: 'Taxonomia' },
  { slug: 'teacher-student' },
  { slug: 'ternary', pt: 'Ternário' },
  { slug: 'testing', pt: 'Testes' },
  { slug: 'test-loop' },
  { slug: 'theme', pt: 'Tema' },
  { slug: 'theming' },
  { slug: 'timezone' },
  { slug: 'tokens' },
  { slug: 'tooluse' },
  { slug: 'tools', pt: 'Ferramentas' },
  { slug: 'training', pt: 'Treinamento' },
  { slug: 'transcription', pt: 'Transcrição' },
  { slug: 'triage', pt: 'Triagem' },
  { slug: 'ttfb' },
  { slug: 'typescript' },
  { slug: 'ui' },
  { slug: 'umami' },
  { slug: 'update' },
  { slug: 'ux' },
  { slug: 'validation', pt: 'Validação' },
  { slug: 'vectorize' },
  { slug: 'vercel' },
  { slug: 'view-transitions' },
  { slug: 'overview', pt: 'Visão Geral' },
  { slug: 'vision' },
  { slug: 'vite' },
  { slug: 'vitest' },
  { slug: 'vlm' },
  { slug: 'vram' },
  { slug: 'vue' },
  { slug: 'watchdog' },
  { slug: 'wave' },
  { slug: 'wave-field' },
  { slug: 'wave-field-theory' },
  { slug: 'wcag' },
  { slug: 'webp' },
  { slug: 'websocket' },
  { slug: 'whisper' },
  { slug: 'windows' },
  { slug: 'workbox' },
  { slug: 'workflow' },
  { slug: 'wsl' },
  { slug: 'wslg' },
  { slug: 'xdist' },
  { slug: 'xss' },
  { slug: 'yaml' },
  { slug: 'zap' },
  { slug: 'covers' },
  { slug: 'knowledge' },
  { slug: 'predictive-navigation' },
  { slug: 'stability' },
  { slug: 'state' },
  // --- adicionados na migração PT->EN (07/09) ---
  { slug: 'python' },
  { slug: 'accessibility' },
  { slug: 'design-tokens' },
  { slug: 'requests' },
  { slug: 'lm-head' },
];

// Alias → slug canônico (PT→EN, plural/singular, variantes).
export const TAG_ALIASES: Record<string, string> = {
  'a11y': 'accessibility',
  'acessibilidade': 'accessibility',
  'agent': 'agents',
  'agente': 'agents',
  'agentes': 'agents',
  'agentes-md': 'agents-md',
  'agentic-review': 'review',
  'alertas': 'alerts',
  'animacao': 'animation',
  'aprendizado': 'learning',
  'arquitetura': 'architecture',
  'artefato': 'artifact',
  'auditoria': 'audit',
  'automacao': 'automation',
  'automatizacao': 'automation',
  'busca': 'search',
  'campo-de-fase': 'wave-field',
  'capa': 'covers',
  'capas': 'covers',
  'cascata': 'cascade',
  'cobertura': 'coverage',
  'codigo': 'code',
  'comeco': 'beginning',
  'confiabilidade': 'reliability',
  'configuracao': 'configuration',
  'conhecimento': 'knowledge',
  'contraste': 'contrast',
  'convergencia': 'convergence',
  'cover': 'covers',
  'decisao': 'decision',
  'dependencias': 'dependencies',
  'deteccao': 'detection',
  'documentacao': 'documentation',
  'ecossistema': 'ecosystem',
  'embedding': 'embeddings',
  'estabilidade': 'stability',
  'estado': 'state',
  'falso-positivo': 'false-positive',
  'ferramentas': 'tools',
  'financas': 'finances',
  'frustracao': 'frustration',
  'gamificacao': 'gamification',
  'hibrida': 'hybrid',
  'ideacao': 'ideation',
  'identidade': 'identity',
  'infra': 'infrastructure',
  'infraestrutura': 'infrastructure',
  'integridade': 'integrity',
  'inventario': 'inventory',
  'jogos': 'games',
  'latencia': 'latency',
  'licoes': 'lessons',
  'limpeza': 'cleanup',
  'lm_head': 'lm-head',
  'maturidade': 'maturity',
  'melhoria': 'improvement',
  'melhorias': 'improvement',
  'memoria': 'memory',
  'migracao': 'migration',
  'monitoramento': 'monitoring',
  'narrativa': 'narrative',
  'navegacao-preditiva': 'predictive-navigation',
  'observabilidade': 'observability',
  'padroes': 'patterns',
  'pedidos': 'requests',
  'persistencia': 'persistence',
  'porta': 'ports',
  'portas': 'ports',
  'privacidade': 'privacy',
  'processo': 'process',
  'processo-continuo': 'continuous-process',
  'producao': 'production',
  'produtividade': 'productivity',
  'progresso': 'progress',
  'projetos': 'projects',
  'qualidade': 'quality',
  'quantizacao': 'quantization',
  'raciocinio': 'reasoning',
  'rede': 'networking',
  'redes': 'networking',
  'refactor': 'refactoring',
  'refatoracao': 'refactoring',
  'reuso': 'reuse',
  'review-agentico': 'review',
  'revisao': 'review',
  'simplicidade': 'simplicity',
  'tema': 'theme',
  'ternario': 'ternary',
  'testes': 'testing',
  'tests': 'testing',
  'transcricao': 'transcription',
  'treinamento': 'training',
  'triagem': 'triage',
  'validacao': 'validation',
  'visao-geral': 'overview',
  'vitrine': 'showcase',
};

export const CANONICAL_SLUGS: Set<string> = new Set(TAG_VOCAB.map(t => t.slug));

export function canonicalizeTag(tag: string): string {
  const key = tag.trim().toLowerCase().replace(/_/g, "-").replace(/\s+/g, "-");
  const c = TAG_ALIASES[key] ?? key;
  // idempotência: se o canonical já é vocab, mantém; senão tenta de-accent
  return c in TAG_ALIASES ? TAG_ALIASES[c] : c;
}

export function tagLabel(slug: string, locale: 'pt' | 'en'): string {
  if (locale === 'en') return slug;
  const def = TAG_VOCAB.find(t => t.slug === slug);
  return def?.pt ?? slug;
}
